### ISSUE TITLE
Proxy w/Authentication support

### ISSUE THREAD

**Issue by giefferre** [parnurzeal/gorequest#10]
It is not clear if the library supports a proxy with authentication.

I tried using 

```
resp, body, errs:= request.Proxy("http://myusername:mypassword@proxyurl:proxyport").Get("http://google.com").End()
```

With no success.

The proxy server is Squid

**Comment by parnurzeal** [comment]
I will close this issue since there is no update.
If there is still the issue on proxy authentication, please reopen it.
