### ISSUE TITLE
Support enabling debug mode by environment variable.

### ISSUE THREAD

**Issue by heytitle** [parnurzeal/gorequest#103]
It would be good if `goreqeust` can be enabled debugging mode once a environment variable, let's say `GOREQUEST_DEBUG=1`, is set.  The idea is borrowed from NodeJS's `request`.

REF:  https://github.com/request/request#debugging

**Comment by QuentinPerez** [comment]
Hi @heytitle 

Thank you for your feedback 😊
Can you do a PR with this feature ?

**Comment by heytitle** [comment]
Yep

**Comment by parnurzeal** [comment]
See #107
