### ISSUE TITLE
How to reuse connection using SuperAgent?

### ISSUE THREAD

**Issue by aiquestion** [parnurzeal/gorequest#105]
according to the comments on go1.6's http.transport and http.client. 
Transport struct will hold connection and re-use it when possible. But seems SuperAgent create a new Transport every time when calling New function.
And SuperAgent cannot be used concurrently.
So what is the suggested way to reuse connection? make a object pool for SuperAgent?

**Comment by parnurzeal** [comment]
You can just reuse it w/o calling New() function again.
Transport is only created when calling New() at the first time.

**Comment by sanchitlohia-ovo** [comment]
@parnurzeal In case I have to reuse the connection then you mentioned I do not need to call New() again. But if I don't call new again then it is not safe to be used my multiple goroutines. So is there any solution to it.
