### ISSUE TITLE
Need to not clean headers in Get, post, put methods

### ISSUE THREAD

**Issue by mdamir** [parnurzeal/gorequest#106]
Get, post and put methods first clean the superagent, hence clearning all the previously set headers. There should be a flag to not clean the headers at least.

**Comment by QuentinPerez** [comment]
Hi @mdamir 

Thank you for your feedback 😊
Can you do a PR with this feature ?

**Comment by dustinrohde** [comment]
Can we get this fix in if possible? This is pretty inhibiting. Thanks :)

**Comment by wmzy** [comment]
Why not use `Clone` instead `ClearSuperAgent`?
