### ISSUE TITLE
queryMap or queryStruct should accept more value type than string

### ISSUE THREAD

**Issue by davyzhang** [parnurzeal/gorequest#119]
```go
func (s *SuperAgent) queryStruct(content interface{}) *SuperAgent {
	if marshalContent, err := json.Marshal(content); err != nil {
		s.Errors = append(s.Errors, err)
	} else {
		var val map[string]interface{}
		if err := json.Unmarshal(marshalContent, &val); err != nil {
			s.Errors = append(s.Errors, err)
		} else {
			for k, v := range val {
				k = strings.ToLower(k)
				s.QueryData.Add(k, v.(string))
			}
		}
	}
	return s
}
```

v.(string) always assume v is a string ,which is not always true in practice, I'd like to add some more basic types such as int,float64, etc, even struct with encoded json string

If you guys ok with this feature, I can cook up a pr.

**Comment by pkopac** [comment]
My project's also affected: It's a bit strange to work with cursor numbers as strings.

Since there's the json.Marshal & json.Unmarshal any number types are converted to float64.
There aren't that many types that can jump out of it. A type switch with proper conversions would be enough.

**Comment by davyzhang** [comment]
I pretty much understand why the author didn't add these quick fixes for this function. It is too hard to find a suitable parameters to convert. See its easy to do a type switch and follow the standard json convert like this:

```
func (s *SuperAgent) queryStruct(content interface{}) *SuperAgent {
	if marshalContent, err := json.Marshal(content); err != nil {
		s.Errors = append(s.Errors, err)
	} else {
		var val map[string]interface{}
		if err := json.Unmarshal(marshalContent, &val); err != nil {
			s.Errors = append(s.Errors, err)
		} else {
			for k, v := range val {
				k = strings.ToLower(k)
				var queryVal string
				switch t := v.(type) {
				case string:
					queryVal = t
				case float64:
					queryVal = strconv.FormatFloat(t, 'f', 6, 64) //what if someone wants 10 precision
				case time.Time:
					queryVal = t.Format(time.RFC3339) //what if the time.Kitchen is preferred
				default:
					j, err := json.Marshal(v)
					if err != nil {
						continue
					}
					queryVal = string(j)
				}
				s.QueryData.Add(k, queryVal)
			}
		}
	}
	return s
}
```

**Comment by pkopac** [comment]
Yes, thank you for writing the solution, that was what I had in mind, too. Would you please create the PR?

For numbers I would use `strconv.FormatFloat(t, 'f', -1, 64)` which conveniently converts to "needed" precision. [See last paragraph here](https://golang.org/pkg/strconv/#FormatFloat). [This proves](https://play.golang.org/p/DacHvmqSwa) even expected integers (event though in float data type) will be integers. If someone needs a _specific_ precision, well, they'll have to round in the struct first. Logical, though.

For time, **always** use standards. Unless presenting to a human. RFC3339 would be the way to go. 
That said, you won't have that problem. Only BSON distinguishes dates, JSON treats them as normal strings. And the go library (Unmarshal) also [doesn't know](https://golang.org/pkg/encoding/json/#Unmarshal) it's a date. So it will be already converted to a string on the first line of the method.

The boolean type is not explicitly mentioned, but it works with the default.

**Comment by davyzhang** [comment]
PR is done #128, waiting for review, test case also updated

**Comment by pkopac** [comment]
This should be closed as a related PR was merged.

**Comment by davyzhang** [comment]
closed
