### ISSUE TITLE
UrlFetch with AppEngine

### ISSUE THREAD

**Issue by athornz** [parnurzeal/gorequest#120]
Does this module support using the UrlFetch client so it can be used on AppEngine?

I've attempted to set the UrlFetch client like:

`
ctx := appengine.NewContext(r)
client := urlfetch.Client(ctx)

var request = gorequest.New()
request.Client = client;
`

But the default http client is still used.

**Comment by athornz** [comment]
Nevermind, this does work, I just had another request not using the urlfetch client.

**Comment by athornz** [comment]
I'm actually still having trouble with this. Is this the recommended way to use gorequest on AppEngine?

I'm getting a `operation not permitted` error when deploying to AppEngine.

**Comment by t0mg** [comment]
Hey @athornz I'm facing the same issue, did you find out how to fix this? 

Thanks

**Comment by athornz** [comment]
Unfortunately this as a long time ago and I can't remember where I got to
