### ISSUE TITLE
Creation of SuperAgent and calling HTTP Method Redundant

### ISSUE THREAD

**Issue by thedillonb** [parnurzeal/gorequest#123]
The creation of a `SuperAgent` object via `gorequest.New()` and the act of calling a HTTP method seems some what redundant. This is due to the fact that the internal state of the `SuperAgent` is getting reset on the verb method via `ClearSuperAgent` which means that any state that you put into the `SuperAgent` object after the object was created is pretty much wiped out. 

This promotes the one liner `gorequest.New().Get(...)...` which then begs the question, is there any reason, if your state gets wiped on calling `Get/Post/Put/...`, to have the creation of the object and the HTTP verb be two different actions? 

Would `gorequest.<Get/Post/Put/...>()` not be sufficient?

**Comment by sapamja** [comment]
I send a pull request to allow user to prevent from clearing up the superagent object stats.

Here is the PR:
https://github.com/parnurzeal/gorequest/pull/109

Please review it.

**Comment by parnurzeal** [comment]
Fix in #140
