### ISSUE TITLE
Multipart request with file upload changes fieldname

### ISSUE THREAD

**Issue by gconan** [parnurzeal/gorequest#126]
Im trying to upload a file to my microservice and I kept getting `"message":"Required MultipartFile parameter 'file' is not present"`. I read your comments and found the issue on line 738 of gorequest.go

Im sure there is a reason that you have that check, but maybe there is another work-around you can do other than overwrite my explicit field name `file`

Thank you

**Comment by jincheny** [comment]
yes, i have encountered the same problem. any one can help?:thinking:

**Comment by jincheny** [comment]
Finnally, i used this. it works. :moyai:  @gconan 
```golang
reqBody := request.Post("https://xxx").Type("multipart").Set("User-Agent", "xxx").Send(`{"xxxxx":"yyyyyy"}`)

reqBody.FileData = append(reqBody.FileData, gorequest.File{
		Filename:  name,
		Fieldname: "file",
		Data:      fileContent,
	})
```

**Comment by gconan** [comment]
@jincheny Thank you!
