### ISSUE TITLE
How can I get error code?

### ISSUE THREAD

**Issue by shimba-boomba** [parnurzeal/gorequest#146]
How can I get error code of request? Is it timeout or refused connection to server? 

    request := gorequest.New()

    request.Timeout(100 * time.Millisecond)

    request.Get("<URL>")

    resp, body, err := request.End()

    if err != nil {
        ? ? ?
    }

**Comment by ror6ax** [comment]
Hi @parnurzeal , can you please help us on this one? Kinda related to https://github.com/parnurzeal/gorequest/issues/158 I guess.

**Comment by ror6ax** [comment]
@shimba-boomba - resp.StatusCode would do, just as in net/http
