### ISSUE TITLE
404 and errors?

### ISSUE THREAD

**Issue by ror6ax** [parnurzeal/gorequest#158]
`resp, body, errs := request.Get("http://google.com/foo/bar").End()` will be a 404, but errs will be an empty array still. 404 html page is in body, so only way to track errors is to parse that.

Pretty sure it's not what we want here.

Need a PR on this?

**Comment by ror6ax** [comment]
@parnurzeal - can you please tell if this is per design?

**Comment by parnurzeal** [comment]
@ror6ax Super sorry for very late reply!

It is by design.
It should have the same behavior with the http package.
Please try:
```
  request := gorequest.New()
  resp, _, errs := request.Get("http://google.com/foo/bar").End()
  fmt.Println(resp, errs)
  resp2, err := http.Get("http://google.com/foo/bar")
  fmt.Println(resp2, err)
```
In short, you should get error code from response object.
Please have a look at this good article.
http://www.metabates.com/2015/10/15/handling-http-request-errors-in-go/
