### ISSUE TITLE
Leaking memory/sockets due to repeated SuperAgent creation

### ISSUE THREAD

**Issue by nicksardo** [parnurzeal/gorequest#16]
Recommend you update the documentation to state that the same SuperAgent be used as much as possible due to the behavior of creating a new http.Transport each time.  Go's HTTP library recycles sockets by using DefaultTransport, which obviously you're not using.  

You could also refactor the code to only create a transport when actually executing the request and when necessary (proxy/timeout operations); otherwise, just use the DefaultTransport.   

For future reference... the package's name is quite misleading with the current API. The package should be named as an `agent` or `client` rather than `request`.  `goagent.New()` is more accurate than `gorequest.New()`.   `gorequest.NewClient()` would be acceptable too, but it's too late for API changes.

**Comment by parnurzeal** [comment]
Hi @nicksardo,

Not sure I understand what you mean correctly. But for GoRequest, it will create a new http.Transport when New() function is called. 

So, if user is creating only once and reuse it. There should be no problem on leaking memory/sockets.

**Comment by nicksardo** [comment]
I'm suggesting you do one of the following:
A) Put a recommendation in the readme to re-use a created agent and warn about the possibility of leaking sockets
B) Change your implementation to only create a new Transport when actually needed (setting up proxy); otherwise use the DefaultTransport

**Comment by parnurzeal** [comment]
Hi Thanks!

I see what you mean now.
I will consider both options.
