### ISSUE TITLE
unable to make request with content type "text/xml" after September 30 commits

### ISSUE THREAD

**Issue by cpacifying** [parnurzeal/gorequest#164]
I am using gorequest to make requests to SOAP server. My code is

```go
agent := gorequest.New().
		Post(endpoint).
		Type("xml").
		Set("Content-Type", "text/xml").
		Set("charset", "utf-8").
		Set("SOAPAction", "login").
		Set("user-agent", "user").
		Send(body)
```

It worked well until recently, but after September 30 commits content type of my request gets implicitly overwritten to "application/xml", which my SOAP server does not accept. Had a look through code and tests, got a feeling this behavior is considered desirable by gorequest developers. Is there any way to keep explicitly set content type?

**Comment by parnurzeal** [comment]
Right now, there is no way to keep the content type. It should be able to it tho so I will tag this as a bug.

Btw, I feel the Sept 30 commits should not create the problem in your case tho.
Are you certain that you didn't have a problem before using the same code?

**Comment by harsimranmaan** [comment]
This is broken by https://github.com/parnurzeal/gorequest/pull/154. Moving the for loop broke the older API. @cpacifying is correct in observing that the latest code breaks the existing client. @parnurzeal

**Comment by parnurzeal** [comment]
@harsimranmaan Got it. Thank you for pointing it out 👍   I will comment in your PR.
