### ISSUE TITLE
Add multipart support

### ISSUE THREAD

**Issue by parnurzeal** [parnurzeal/gorequest#20]

**Comment by skhro87** [comment]
+1 
Would be very nice to have.

**Comment by alecdwm** [comment]
+1

**Comment by npkumar** [comment]
+1 
application/x-www-form-urlencoded would also be nice

**Comment by rwaweber** [comment]
+1, here is something that I used to satisfy multipart requirements. I bet that something could be cobbled together from bits and pieces of this. 

http://stackoverflow.com/questions/20205796/golang-post-data-using-the-content-type-multipart-form-data

**Comment by Misfit-John** [comment]
+10086

**Comment by fraenky8** [comment]
I have a partial solution right now. First i worked on issue #79, but then i realized that this issue is the more common case. I already got the file upload working. Next step is to combine the data to send and the file upload. I will introduce a new method like `SendFile` which accepts either `string` or `[]bytes` and a new field like `FileData` of type `map[string][]byte` which holds the filename => fileContent in bytes.

Any suggestions before working on?

**Comment by Misfit-John** [comment]
@fraenky8 I was planning to do it by myself yesterday, now I can count on you now... Just wanna remind that Form data is not like a map. Form data is map[string][]string and map[string][]*FileHeader  , so One key can has multiple values. refer to package "mime/multipart".

**Comment by fraenky8** [comment]
I don't know the workflow here at git, so i finished the feature at my fork:
https://github.com/fraenky8/gorequest
Clone it locally (i think `go get ...` will not work for some reasons?) and switch to branch 
`multipart-feature`. Here is a example for how to using it: (assuming `file1.txt` and `file2.txt` exist)

```go
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"path/filepath"

	"github.com/fraenky8/gorequest"
)

type TestStruct struct {
	String      string
	Int         int
	Btrue       bool
	Bfalse      bool
	Float       float64
	StringArray []string
	IntArray    []int
	BoolArray   []bool
	FloatArray  []float64
}

func main() {
	debug := true

	httpClient := gorequest.New()
	httpClient.Debug = debug

	file2, _ := filepath.Abs("./file2.txt")
	b, _ := ioutil.ReadFile(file2)

	_, body, errs := httpClient.Post("http://httpbin.org/post").
		Type("multipart").
		Send(`{"query1":"test"}`).
		Send(TestStruct{
			String:      "a string",
			Int:         42,
			Btrue:       true,
			Bfalse:      false,
			Float:       12.345,
			StringArray: []string{"string1", "string2"},
			IntArray:    []int{1, 2},
			BoolArray:   []bool{true, false},
			FloatArray:  []float64{1.23, 4.56, 7.89},
		}).
		Send([]string{`string1`, "string2"}).Set("json_fieldname", `my_data`).
		Send([2]string{"string1", "string2"}).
		Send("param=1").
		Send("param=2").
		Send("param=3&param=4").
		SendFile("./file1.txt", "", "").
		SendFile(b, "file2.txt", "my_file_2").
		End()

	if len(errs) > 0 {
		for _, err := range errs {
			fmt.Println(err)
		}
	}

	if !debug {
		log.Println(body)
	}
}
```
The ouput is something like https://gist.github.com/fraenky8/19feccf21a1a4e2a6d8999717c3334b9

It still lacks at documentation and examples (SendFile method), but i think it works well so far. Furthermore the readme must be updated with examples, before we merge the upcoming PR.

**Comment by fraenky8** [comment]
The PR is merged, so the feature is live now! Let us know, if anything is unclear or missing! (in a new bug request)

This issue can be closed.

**Comment by parnurzeal** [comment]
This is very impressive. Thank you!
