### ISSUE TITLE
Auto decompress body

### ISSUE THREAD

**Issue by matrixik** [parnurzeal/gorequest#23]
Hi,

Thank you for this useful package.

Looks like now you simply return body even if it is compressed.
Maybe you can automatically decompress body when you find `Content-Encoding: gzip` header.

Go `net/http` is doing that already.

**Comment by coderhaoxin** [comment]
It seems `go` will do that.

http://golang.org/pkg/net/http/#Transport

**Comment by matrixik** [comment]
OK,

I found my problem:
```go
package main

import (
	"fmt"
	"github.com/parnurzeal/gorequest"
)
func main(){
	_, body, _ := gorequest.New().Get("http://httpbin.org/gzip").
		Set("Accept-Encoding", "gzip").
		End()
	fmt.Printf("%#v\n\n", body)
}
```
When I run this program `body` is compressed. But when line `Set("Accept-Encoding", "gzip").` is removed `body` is decompressed.
`http://httpbin.org/gzip` is always returning gzipped content.

Looks like a bug to me.

**Comment by parnurzeal** [comment]
Hi @matrixik ,

I have checked. 
In both case (with or w/o "Accept-Encoding":"gzip" ), GoRequest is acting exactly the same with Go `net/http` as in your example.

```
package main

import (
        "fmt"
        "io/ioutil"
        "net/http"

        "github.com/parnurzeal/gorequest"
)

func main() {
        _, body1, _ := gorequest.New().Get("http://httpbin.org/gzip").
                Set("Accept-Encoding", "gzip").
                End()

        client := &http.Client{}
        req, _ := http.NewRequest("GET", "http://httpbin.org/gzip", nil)
        req.Header.Add("Accept-Encoding", "gzip")

        resp, _ := client.Do(req)
        bodyByte, _ := ioutil.ReadAll(resp.Body)
        body2 := string(bodyByte)
        defer resp.Body.Close()
        fmt.Println(body1)
        fmt.Println(body2)
}
```
Please let me know if this is not the case.

**Comment by matrixik** [comment]
It's probably something on my end, sorry for trouble.

**Comment by zhaohansprt** [comment]
what about upload a  gzip file to server? does the http/net auto  compress it according to the header?
