### ISSUE TITLE
Package broken with dependency "http2curl"

### ISSUE THREAD

**Issue by tonytcb** [parnurzeal/gorequest#235]
Hello. I'm facing the below issue using de tag v0.2.15.

Can I fix this in my app?

```
../github.com/parnurzeal/gorequest/gorequest.go:31:2: cannot find package "github.com/moul/http2curl" in any of:
	/usr/local/go/src/github.com/moul/http2curl (from $GOROOT)
	/go/src/github.com/moul/http2curl (from $GOPATH)
```
It started today, before, was running perfect.

Thanks,

**Comment by moul** [comment]
Related with https://github.com/moul/http2curl/issues/20

**Comment by tonytcb** [comment]
Hi @moul . I really appreciate your help.
I saw your PR was acepted in the "develop" branch, but there is not a new tag released to this package.
Fow now, you believe the best option is use the branch "develop" even in production? It's safe?
Do you know about the new release tag?

Thanks,

**Comment by moul** [comment]
@QuentinPerez maybe you can help adding a new tag?

**Comment by moul** [comment]
@tonytcb from what I see, the develop branch is the default one for this repo, and master branch wasn't updated for years

as develop is default branch for github, most of the clients (if not all) are pulling develop when you ask for "latest"

so, my feeling is yes, develop is the new master and can be used in production

however, it may be cleaner to set a git tag, which will remove the ambiguity

**Comment by QuentinPerez** [comment]
Just create a new tag from the develop branch.

Let me know if you still have the issue

**Comment by tonytcb** [comment]
It's working well now!
