### ISSUE TITLE
Keys of query params are incorrectly converted to lower case when in form of map.

### ISSUE THREAD

**Issue by wuhan005** [parnurzeal/gorequest#253]
When send map as query params, all the keys will be lower case.

For example:
```go
gorequest.New().Get("http://localhost/").Query(map[string]string{"Foo": "bar", "QWE": "RTY"}).End()
```
It will request the url `http://localhost/?foo=bar&qwe=RTY`, the expected is `http://localhost/?Foo=bar&QWE=RTY`.

For the `queryMap()` call the `queryStruct()` and the keys have been converted to lower case at https://github.com/parnurzeal/gorequest/blob/develop/gorequest.go#L539

**Comment by llqgit** [comment]
It's so stupid auto change charactor case. It's a bug. Fix it please........

**Comment by wklken** [comment]
https://github.com/wklken/gorequest/pull/7
