### ISSUE TITLE
wrong type convert in send method

### ISSUE THREAD

**Issue by sdhjl2000** [parnurzeal/gorequest#31]
not matter i set a struct or string into send method,inside it auto convert {"DealerId":2004410,"IPAddress":"36.59.237.195"} to {"DealerId":2.00441e+06,"IPAddress":"36.59.237.195"},finally i find the json lib auto convert it( http://stackoverflow.com/questions/22343083/json-marshaling-with-long-numbers-in-golang-gives-floating-point-number ),so everyone have a struct with int should care about this ,haven't find any solution for this, i think in the SendString method should not Unmarshal again

**Comment by parnurzeal** [comment]
Thanks for pointing this out.
The fix will be released in next version.

**Comment by sdhjl2000** [comment]
well done,3ks
