### ISSUE TITLE
HTTP Authentication is Broken

### ISSUE THREAD

**Issue by csquared** [parnurzeal/gorequest#39]
For authentication *other* than HTTP Basic (bearer auth for something like web tokens) this will not work:

https://github.com/parnurzeal/gorequest/blob/master/main.go#L541-L545

And will effectively nuke any manually set Authorization headers.  I had to comment out line 544 to get things working again (I am using Bearer Auth).  Is deleting the else half of this branch sufficient? If so, I'll happily send over a pull request. Or maybe I should just switch over to `goreq` ?

**Comment by bradleyankrom** [comment]
Ugh, I just ran into this, too. 

    (type *gorequest.SuperAgent has no field or method SetBasicAuth)

**Comment by parnurzeal** [comment]
Thanks for pointing out.
@na-ga has also already sent a PR #38. 
I will merge it soon.

**Comment by na-ga** [comment]
Thanks!

**Comment by csquared** [comment]
Thanks!
