### ISSUE TITLE
Don't support array when post json data

### ISSUE THREAD

**Issue by Shanicky** [parnurzeal/gorequest#40]
Hi
I met some problems when post data like this

```json
[
  {
    "a":1
  },
  {
    "a":2
  }
]
```

Does it support array when posting json data?
Thanks a lot

**Comment by Brasilikum** [comment]
I asked myself the same thing. Line 381 in the [sourcecode](https://github.com/parnurzeal/gorequest/blob/master/main.go) shows that slices are not (yet) supported.  I now think adding them is not that simple, because slices do not have a key. A key is needed because you are able to call .Send() multiple times. I am proposing an additional Function:

```go
array := []string{"one", "two", "three"}
gorequest.Post("http://abc.com").SendArray(array, "myKey").Send(´{"add": "json"}´).End()
//Server recieves: {"myKey": ["one", "two", "three"], "add": "json"}}

gorequest.Post("http://abc.com").SendArray(array, "myKey").End()
//Server recieves: ["one", "two", "three"]
```

Thoughts?

**Comment by romainletendart** [comment]
Hi!
Arrays are already supported if being sent as a value inside a key-value pair.
And this works either the JSON way:
```go
gorequest.Post("http://abc.com").Send(`{"values":["test1","test2","test3"]}`).End()
```
Or, the Go way:
```go
type Data struct {
        Values []string `json:"values"`
}
myData := Data{Values: []string{"test1", "test2", "test3"}}
gorequest.Post("http://abc.com").Send(myData).End()
```

Both will result in the server receiving:
```json
{"values":["test1","test2","test3"]}
```

**Comment by parnurzeal** [comment]
Thanks @Brasilikum for the idea. Yours should work well too.
But I want to hide it from the user. User should not think too much and can just use Send() to do it.
Please have a look. If you think you want to improve it, please don't hesitate to just send me a pull request. Thanks!

Also, thanks @romainletendart for helping answering the question.
