### ISSUE TITLE
Add support for unmarshaling the response body into struct

### ISSUE THREAD

**Issue by brasilikum** [parnurzeal/gorequest#41]
How about adding support for something like this:

```go
type Person struct {
  Name string
}

var friend Person
response, _, errs := request.Post("http://example.com").BindBody(&friend).End()
```

**Comment by ghophp** [comment]
:+1:

**Comment by fraenky8** [comment]
Can be closed due EndStruct()-Feature: https://github.com/parnurzeal/gorequest/pull/88

**Comment by marioluan** [comment]
The feature was added to master branch, but it is not available under a tag release.

The last one we have is `v0.12.13`, which does not include EndStruct support.

Is there any chance to generate another tag to include those changes?
cc @fraenky8 @QuentinPerez @franciscocpg

**Comment by franciscocpg** [comment]
Hi @marioluan, I am not project owner so it is not possible for me.
But if you are using `glide` you can refer to a single commit, this way:
```yaml
  - package: github.com/parnurzeal/gorequest
    version: 6e8ad4ebdee4bec2934ed5afaaa1c7b877832a17
```

**Comment by QuentinPerez** [comment]
Hi @marioluan, I can't merge on the master branch but I created a new tag `v0.2.14` can you tell me if it is enough for you ?

**Comment by marioluan** [comment]
Thanks @franciscocpg @QuentinPerez!
