### ISSUE TITLE
Unable to mock requests on tests

### ISSUE THREAD

**Issue by pires** [parnurzeal/gorequest#47]
If I use `net/http` way of doing the client, it works. With `gorequest` it doesn't. How can one achieve such behavior?

**Comment by pires** [comment]
[I now have it working](https://github.com/jarcoal/httpmock/pull/6) but want feedback before thinking of a PR. I mean, obviously the solution here shouldn't be to comment https://github.com/parnurzeal/gorequest/blob/master/main.go#L565.

**Comment by parnurzeal** [comment]
Sorry, I was traveling outside of country this past month. 
Anyway, this sounds good to me. Please send the PR. 

Thanks!

**Comment by parnurzeal** [comment]
Fix in PR #59

**Comment by techygarg** [comment]
@pires : I am trying to use gorequest and want to mock http calls with "jarcoal/httpmock" but it is not working. I think I am missing some bits of it. Can you please share a small code snippet or refer some link where you have implemented gorequest with jarcoal/httpmock.
