### ISSUE TITLE
Headers not setting?

### ISSUE THREAD

**Issue by cathalgarvey** [parnurzeal/gorequest#49]
Setting headers doesn't work. Searching for 'Header.Set' in the repo, I can't find any occurrences that aren't hard-coded; that is, there doesn't seem to be any code linking the gorequest 'Set' method to the builtin http methods.

The below example, for me, displays the SuperAgent struct as containing the correct headers, but the returned data shows none of these headers, only the set seemingly built-in to Golang's http libs.

```Go
package main

import (
    "fmt"
    "github.com/parnurzeal/gorequest"
)

func main() {
    requestor := gorequest.New()
    requestor.Set("User-Agent", "Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0")
    requestor.Set("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
    fmt.Println(requestor)
    _, body, _ := requestor.Get("https://httpbin.org/headers").End()
    fmt.Println(body)
}
```

**Comment by smallnest** [comment]
Get/Post/Head/... clears the SuperAgent so what you set will be lost.

try this and you will get the right result.
``` 
func main() {
    requestor := gorequest.New().Get("https://httpbin.org/headers")
    requestor.Set("User-Agent", "Mozilla/5.0 (X11; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0")
    requestor.Set("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
    fmt.Println(requestor.Header)
    _, body, _ := requestor.End()
    fmt.Println(body)
}
```
I think any document should indicate this.

**Comment by cathalgarvey** [comment]
Thanks for the help! That isn't really clear in the documentation, and I think intuitively it's confusing; headers ought to be reset on `End` rather than on `<HTTP Method>`.

It may not be the case that a request actually happens on using the `<HTTP Method>` methods, but that's what one feels; that calling the method is the last logical step in the process unless you're doing some chunked wizardry.

There's also the question of headers and other parameters that may be intended as "usual reasonable defaults"; my browser *always* sends its user-agent, so why shouldn't my go application know to do this always without explicit instruction? A way to set defaults like language, user agent, and compression headers would be nice.

Anyways, thanks. PEBKAC in this case but IMO suggests confusion in the docs or interface.
