### ISSUE TITLE
gorequest install problems

### ISSUE THREAD

**Issue by csrgxtu** [parnurzeal/gorequest#50]
i am using ubuntu and muanlly install go in my home dir with GOPATH all set. and got this:
package golang.org/x/net/publicsuffix: unrecognized import path "golang.org/x/net/publicsuffix"

**Comment by wiennat** [comment]
Have you tried `go get  golang.org/x/net/publicsuffix` to install publicsuffix package?

**Comment by csrgxtu** [comment]
wheather i install gorequest or get golang.org/x/net/publicsuffix, all get this problem:
package golang.org/x/net/publicsuffix: unrecognized import path "golang.org/x/net/publicsuffix"

**Comment by wiennat** [comment]
I have tried installing `gorequest` from scratch and found no problem.
Does this error show for only gorequest? Do you have any problem using other 3rd party packages?

**Comment by csrgxtu** [comment]
have a look at this pic:
![screenshot from 2015-09-28 01 39 51](https://cloud.githubusercontent.com/assets/5053620/10128527/ea9f71f4-6581-11e5-9d9e-3f01d44b36a9.png)

**Comment by wiennat** [comment]
Could you try running `go get -v golang.org/x/net/publicsuffix`?
What does `curl -v golang.org/x/net/publicsuffix` say?

One thread I found said that golang.org is blocked in China.  If that is the case, please follow the instruction in [this thread](https://groups.google.com/forum/#!topic/golang-nuts/XFqD-ccA9rY).

**Comment by csrgxtu** [comment]
well not seem like blocked in China, I use proxychains get the content but still can't:
![screenshot from 2015-09-28 02 12 33](https://cloud.githubusercontent.com/assets/5053620/10128930/872c41e2-6586-11e5-884c-e745cdd8b8da.png)

**Comment by wiennat** [comment]
Then I have no idea what's going on.  :sweat:

**Comment by csrgxtu** [comment]
@wiennat en, thank u anyway.

**Comment by parnurzeal** [comment]
@csrgxtu  
Can you try any other package?
Do you have any problem getting other packages beside gorequest and publicsuffix?

**Comment by wiennat** [comment]
@parnurzeal he can install gopkg.in/mgo.v2 .

@csrgxtu I am wondering if proxychains works correctly.

**Comment by csrgxtu** [comment]
@wiennat ok, i will try it with a VPN, to verify it is the network problem. and if it is i will report here.

**Comment by csrgxtu** [comment]
well, the install problem solved, it is because the Chinese Gov banned the golang website, after i using VPN, it worked. thanks man.

**Comment by wiennat** [comment]
Good to know that :)

Cheers
