### ISSUE TITLE
Disable SSL certificate checks

### ISSUE THREAD

**Issue by carlskii** [parnurzeal/gorequest#54]
Hi,

Using the net/http library I can do something like this to disable cert checks: 

```go
tr := &http.Transport{
TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
}
```

Can this be configured for use with gorequest ?

Thanks.

**Comment by charliedrage** [comment]
@carlskii you can do this under TLSClientConfig :)

**Comment by parnurzeal** [comment]
That's right. 
You can do this by just set TLSClientConfig for GoRequest. 
See code below.

https://github.com/parnurzeal/gorequest/blob/master/main.go#L348

**Comment by NoGroceries** [comment]
gorequest.New().TLSClientConfig(&tls.Config{ InsecureSkipVerify: true}).
       Get("https://disable-security-check.com").
       End()
