### ISSUE TITLE
Add a retry function 

### ISSUE THREAD

**Issue by parnurzeal** [parnurzeal/gorequest#6]
A suggestion by Dobrosław Żybort
https://groups.google.com/d/msg/golang-nuts/Pqu94CxcJ24/IsiyV0tEU9UJ

**Comment by xild** [comment]
I'm thinking in something like that: 

```
   gorequest.New().
     Post("/gamelist").
     Retryable(3, 5000 * time.seconds, http.StatusBadRequest, http.StatusInternalServerError).
     End()
```

So when the request get a 400 or 500, a new attempt will fire every 5 seconds until the max attempt reach, in this case 3. 

@parnurzeal What do you think?

Thank you!

**Comment by cizixs** [comment]
I think this issue should be closed.
