### ISSUE TITLE
Can't get *http.Request from *SuperAgent

### ISSUE THREAD

**Issue by quangbuule** [parnurzeal/gorequest#68]
In case to do testing, I need *http.Request but I can't get *http.Request from *SuperAgent.

https://golang.org/pkg/net/http/httptest/#example_ResponseRecorder

**Comment by QuentinPerez** [comment]
Hi @quangbuule, have you tried to cast like this ```(*http.Response)(resp)``` ?

**Comment by quangbuule** [comment]
Hi @QuentinPerez, I mean `*http.Request`, not `*http.Response`.

**Comment by parnurzeal** [comment]
Hi @quangbuule, there is *http.Request in *SuperAgent. It is called and handled inside Gorequest's End() function. I can't see an easy way to get *http.Request from *Superagent.

Except fixing the code to explicitly return *http.Request from End().

**Comment by quangbuule** [comment]
I know that, so is it good to have that? I would like to do pull request on this: write a method to return *http.Request, then reuse it in End().

**Comment by parnurzeal** [comment]
Hi @quangbuule, it is good to have as it is needed by your use case.
