### ISSUE TITLE
How to prevent `ClearSuperAgent()` when GET or POST?

### ISSUE THREAD

**Issue by imWildCat** [parnurzeal/gorequest#76]
I'm writing a crawler so I have to add some headers(User Agent, Cookies) for SuperAgent to simulate a browser.
But when I executed `Get()` method, it would remove all the headers I set.
How to prevent it?

**Comment by parnurzeal** [comment]
Sorry for late reply.
By default, all the Get(), Post(), or other HTTP method functions should be declared at the beginning before using other functionalities.

The reason behind this is for the reusability of GoRequest. It is more expected for users to clear agent when requesting to a new urls.

That is being said. You should:
request := GoRequest.New()
request.Get("url1").push_any_other_method_here_after_Get().End()
