### ISSUE TITLE
Bool fields are getting ignored when Post type is "form"

### ISSUE THREAD

**Issue by sheenobu** [parnurzeal/gorequest#86]
The bug is here: https://github.com/parnurzeal/gorequest/blob/85e45d300dea2897330729470524f2eaf2d7896e/main.go#L577

We are only looking for strings and numbers but SendStruct adds the boolean directly and gets skipped on s.Data key/value iteration.

https://github.com/parnurzeal/gorequest/blob/85e45d300dea2897330729470524f2eaf2d7896e/main.go#L520

**Comment by fraenky8** [comment]
Can be closed due PR https://github.com/parnurzeal/gorequest/pull/93
