### ISSUE TITLE
Middleware support

### ISSUE THREAD

**Issue by yort** [parnurzeal/gorequest#97]
Hi Guys,

Is there any support for middleware in gorequest? I've had a look through the code and nothing stands out.

If there isn't middleware support is there a way to hack something in outside of gorequest to accomplish the same thing?

The situation I have is that I am interacting with some internal endpoints which use nonstandard authentication (not oauth for example), which randomly redirect you to a login endpoint, I need to be able to detect this happening, if it does then I need to submit a login request to get a new access key, and then continue with the original request.

Hope that all makes sense.

Thanks
YorT/Troy

**Comment by parnurzeal** [comment]
You can use [RedirectPolicy](https://github.com/parnurzeal/gorequest/blob/develop/gorequest.go#L482)

Sorry for bad documentation but please see how to use it in [the original http/net's CheckRedirect function](https://golang.org/pkg/net/http/).
